apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: patient-system
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 4004
      targetPort: 4004
  type: ClusterIP
