apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: patient-system-secrets
  namespace: patient-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: patient-system-secrets
    creationPolicy: Owner
  data:
    - secretKey: rds-address
      remoteRef:
        key: patient-system/prod
        property: rds-address
    - secretKey: db-password
      remoteRef:
        key: patient-system/prod
        property: db-password
    - secretKey: msk-bootstrap-brokers
      remoteRef:
        key: patient-system/prod
        property: msk-bootstrap-brokers
    - secretKey: opensearch-endpoint
      remoteRef:
        key: patient-system/prod
        property: opensearch-endpoint
    - secretKey: cognito-user-pool-id
      remoteRef:
        key: patient-system/prod
        property: cognito-user-pool-id
    - secretKey: s3-bucket-name
      remoteRef:
        key: patient-system/prod
        property: s3-bucket-name
    - secretKey: import-queue-url
      remoteRef:
        key: patient-system/prod
        property: import-queue-url
