apiVersion: v1
kind: ServiceAccount
metadata:
  name: organization-service
  namespace: patient-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::303357409766:role/prod-organization-service
