server:
  port: 4004

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/patientmanagement/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
            - id: billing-service-route
              uri: http://billing-service:4001
              predicates:
                - Path=/api/billing/**
            - id: treatment-route
              uri: http://treatment-service:4003
              predicates:
                - Path=/api/treatments/**
            - id: category-route
              uri: http://treatment-service:4003
              predicates:
                - Path=/api/categories/**
            - id: search-service-route
              uri: http://search-service:8080
              predicates:
                - Path=/api/search/**
            - id: analytics-service-route
              uri: http://analytics-service:4002
              predicates:
                - Path=/api/analytics/**
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patient
              filters:
                - RewritePath=/api-docs/patient,/v3/api-docs
            - id: api-docs-billing-route
              uri: http://billing-service:4001
              predicates:
                - Path=/api-docs/billing
              filters:
                - RewritePath=/api-docs/billing,/v3/api-docs

jwt:
  issuer-uri: https://api.patientsystem.me/realms/patientmanagement
