apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: patient-system
spec:
  selector:
    app: patient-service
  ports:
    - name: http
      port: 4000
      targetPort: 4000
    - name: grpc
      port: 9003
      targetPort: 9003
  type: ClusterIP
