INSERT INTO category (id, name, description) VALUES
    (gen_random_uuid(), 'Surgery', 'Surgical procedures and operations'),
    (gen_random_uuid(), 'Consultation', 'Medical consultations and specialist visits'),
    (gen_random_uuid(), 'Diagnostics', 'Laboratory tests and diagnostic procedures'),
    (gen_random_uuid(), 'Radiology', 'Imaging and radiology procedures'),
    (gen_random_uuid(), 'Physical Therapy', 'Physical and occupational therapy sessions'),
    (gen_random_uuid(), 'Emergency', 'Emergency medical care and trauma'),
    (gen_random_uuid(), 'Preventive Care', 'Vaccinations and preventive health screenings'),
    (gen_random_uuid(), 'Mental Health', 'Mental health and behavioral therapy'),
    (gen_random_uuid(), 'Cardiology', 'Cardiac diagnostics and procedures')
ON CONFLICT (name) DO NOTHING;

INSERT INTO treatment (id, name, category_id, price)
SELECT gen_random_uuid(), t.name, c.id, t.price
FROM (VALUES
    ('Appendectomy', 'Surgery', 15000.00),
    ('Hip Replacement', 'Surgery', 25000.00),
    ('Knee Replacement', 'Surgery', 22000.00),
    ('Cataract Surgery', 'Surgery', 3500.00),
    ('Gallbladder Removal', 'Surgery', 12000.00),
    ('Hernia Repair', 'Surgery', 8000.00),
    ('Tonsillectomy', 'Surgery', 4500.00),
    ('Spinal Fusion', 'Surgery', 45000.00),
    ('Heart Bypass Surgery', 'Surgery', 80000.00),
    ('Rhinoplasty', 'Surgery', 6000.00),
    ('General Consultation', 'Consultation', 150.00),
    ('Specialist Consultation', 'Consultation', 350.00),
    ('Pediatric Consultation', 'Consultation', 200.00),
    ('Cardiology Consultation', 'Consultation', 400.00),
    ('Neurology Consultation', 'Consultation', 450.00),
    ('Psychiatry Consultation', 'Consultation', 300.00),
    ('Oncology Consultation', 'Consultation', 500.00),
    ('Second Opinion Consultation', 'Consultation', 350.00),
    ('Blood Test Panel', 'Diagnostics', 250.00),
    ('Urine Analysis', 'Diagnostics', 80.00),
    ('Cholesterol Panel', 'Diagnostics', 120.00),
    ('Complete Blood Count', 'Diagnostics', 100.00),
    ('Thyroid Function Test', 'Diagnostics', 180.00),
    ('HbA1c Test', 'Diagnostics', 90.00),
    ('Liver Function Test', 'Diagnostics', 150.00),
    ('COVID-19 PCR Test', 'Diagnostics', 120.00),
    ('X-Ray', 'Radiology', 200.00),
    ('MRI Brain', 'Radiology', 1500.00),
    ('CT Scan Abdomen', 'Radiology', 1200.00),
    ('Ultrasound', 'Radiology', 400.00),
    ('Mammography', 'Radiology', 300.00),
    ('PET Scan', 'Radiology', 3500.00),
    ('Bone Density Scan', 'Radiology', 250.00),
    ('Chest X-Ray', 'Radiology', 150.00),
    ('Initial PT Assessment', 'Physical Therapy', 200.00),
    ('Physical Therapy Session', 'Physical Therapy', 120.00),
    ('Hydrotherapy Session', 'Physical Therapy', 150.00),
    ('Occupational Therapy', 'Physical Therapy', 130.00),
    ('Emergency Room Visit', 'Emergency', 1500.00),
    ('Ambulance Transport', 'Emergency', 800.00),
    ('Emergency Surgery', 'Emergency', 20000.00),
    ('Trauma Care', 'Emergency', 5000.00),
    ('Annual Physical Exam', 'Preventive Care', 250.00),
    ('Flu Vaccination', 'Preventive Care', 40.00),
    ('COVID-19 Vaccination', 'Preventive Care', 30.00),
    ('HPV Vaccination', 'Preventive Care', 250.00),
    ('Psychotherapy Session', 'Mental Health', 200.00),
    ('Cognitive Behavioral Therapy', 'Mental Health', 220.00),
    ('Group Therapy Session', 'Mental Health', 100.00),
    ('Electrocardiogram (ECG)', 'Cardiology', 300.00)
) AS t(name, category_name, price)
JOIN category c ON c.name = t.category_name
ON CONFLICT (name) DO NOTHING;
