spring.application.name=billingservice

server.port=4001
grpc.server.port=9001

spring.datasource.url=jdbc:postgresql://localhost:5434/billing_db
spring.datasource.username=admin_user
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.patientsystem.billingservice.multitenancy.TenantIdentifierResolver
spring.jpa.properties.hibernate.multi_tenant_connection_provider=com.patientsystem.billingservice.multitenancy.MultitenantConnectionProvider

