events {}

http {
    server {
        listen 80;
        server_name patientsystem.duckdns.org;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name patientsystem.duckdns.org;

        ssl_certificate /etc/letsencrypt/live/patientsystem.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/patientsystem.duckdns.org/privkey.pem;

        # Keycloak routes
        location ~ ^/(realms|resources|js|admin)/ {
            proxy_pass http://keycloak:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        # API Gateway
        location / {
            proxy_pass http://api-gateway:4004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
