events {}

http {
    server {
        listen 80;
        server_name patientsystem.me www.patientsystem.me;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name patientsystem.me www.patientsystem.me;

        ssl_certificate /etc/ssl/cloudflare/cert.pem;
        ssl_certificate_key /etc/ssl/cloudflare/key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Keycloak routes
        location ~ ^/(realms|resources|js|admin|welcome)/ {
            proxy_pass http://keycloak:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        # API Gateway
        location / {
            proxy_pass http://api-gateway:4004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
