apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: patient-system
spec:
  selector:
    app: billing-service
  ports:
    - name: http
      port: 4001
      targetPort: 4001
    - name: grpc
      port: 9001
      targetPort: 9001
  type: ClusterIP
