spring.application.name=patient-service
server.port=4000
grpc.server.port=9003
logging.level.root=INFO
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.patientsystem.patientservice.multitenancy.TenantIdentifierResolver
