spring.application.name=organizationservice

server.port=4005

spring.datasource.url=jdbc:postgresql://localhost:5437/organization_db
spring.datasource.username=admin_user
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

grpc.client.patient-service.address=static://${PATIENT_SERVICE_ADDRESS:localhost}:${PATIENT_SERVICE_GRPC_PORT:9003}
grpc.client.patient-service.negotiation-type=plaintext
grpc.client.billing-service.address=static://${BILLING_SERVICE_ADDRESS:localhost}:${BILLING_SERVICE_GRPC_PORT:9001}
grpc.client.billing-service.negotiation-type=plaintext
grpc.client.treatment-service.address=static://${TREATMENT_SERVICE_ADDRESS:localhost}:${TREATMENT_SERVICE_GRPC_PORT:9002}
grpc.client.treatment-service.negotiation-type=plaintext
grpc.client.analytics-service.address=static://${ANALYTICS_SERVICE_ADDRESS:localhost}:${ANALYTICS_SERVICE_GRPC_PORT:9004}
grpc.client.analytics-service.negotiation-type=plaintext
aws.cognito.user-pool-id=eu-west-1_Sb4mcDano
aws.region=eu-west-1