spring.application.name=organizationservice

server.port=4005

spring.datasource.url=jdbc:postgresql://localhost:5437/organization_db
spring.datasource.username=admin_user
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

aws.cognito.user-pool-id=eu-west-1_Sb4mcDano
aws.region=eu-west-1