spring.application.name=analyticsservice

server.port=4002
grpc.server.port=9004

spring.datasource.url=jdbc:postgresql://localhost:5435/analytics_db
spring.datasource.username=admin_user
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.kafka.consumer.group-id=analytics-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.patientsystem.analyticsservice.multitenancy.TenantIdentifierResolver
spring.jpa.properties.hibernate.multi_tenant_connection_provider=com.patientsystem.analyticsservice.multitenancy.MultitenantConnectionProvider