apiVersion: v1
kind: Service
metadata:
  name: treatment-service
  namespace: patient-system
spec:
  selector:
    app: treatment-service
  ports:
    - name: http
      port: 4003
      targetPort: 4003
    - name: grpc
      port: 9002
      targetPort: 9002
  type: ClusterIP
